#!/usr/bin/env python3
"""
Replot Butterfly Laser side-fringe lock recording bundles.

Usage:
  python3 plot_lock_recording.py ~/Butterfly_Laser_Data/my_run/event_dir
  python3 plot_lock_recording.py ~/Butterfly_Laser_Data/my_run --recursive

The script expects files generated by the Tauri Lock page:
  metadata.json
  reference_spectrum.csv
  lock_sweep_frame.csv
  lock_sweep_partial_estimated.csv
  pd_temperature_monitor.csv
  lock_status.csv
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path
from typing import Any, Iterable


def parse_cell(value: str) -> Any:
    text = value.strip()
    if text == "":
      return ""
    try:
        number = float(text)
    except ValueError:
        return value
    if math.isfinite(number) and number.is_integer():
        return int(number)
    return number


def read_csv_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        return [{key: parse_cell(value) for key, value in row.items()} for row in reader]


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    return data if isinstance(data, dict) else {}


def discover_recording_dirs(root: Path) -> list[Path]:
    root = root.expanduser().resolve()
    if (root / "metadata.json").exists():
        return [root]
    return sorted(path.parent for path in root.rglob("metadata.json"))


def resolve_output_dir(event_dir: Path, output: str | None) -> Path:
    return Path(output).expanduser().resolve() if output else event_dir / "plots"


def column(rows: list[dict[str, Any]], name: str) -> list[float]:
    values: list[float] = []
    for row in rows:
        value = row.get(name)
        if isinstance(value, (int, float)) and math.isfinite(value):
            values.append(float(value))
    return values


def has_columns(rows: list[dict[str, Any]], *names: str) -> bool:
    if not rows:
        return False
    return all(name in rows[0] for name in names)


def first_number(metadata: dict[str, Any], *paths: str) -> float | None:
    for path in paths:
        node: Any = metadata
        for part in path.split("."):
            if not isinstance(node, dict) or part not in node:
                node = None
                break
            node = node[part]
        if isinstance(node, (int, float)) and math.isfinite(node):
            return float(node)
    return None


def add_vertical_marker(ax: Any, x: float | None, label: str, color: str) -> None:
    if x is None:
        return
    ax.axvline(x, color=color, linestyle="--", linewidth=1.2, alpha=0.85)
    _, ymax = ax.get_ylim()
    ax.text(x, ymax, f" {label}", color=color, fontsize=8, va="top")


def setup_matplotlib() -> Any | None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        return plt
    except ImportError:
        return None


def svg_escape(value: Any) -> str:
    return str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def padded_range(values: list[float]) -> tuple[float, float]:
    finite = [value for value in values if math.isfinite(value)]
    if not finite:
        return 0.0, 1.0
    low = min(finite)
    high = max(finite)
    span = high - low
    if span <= 0:
        span = max(1.0, abs(high) * 0.05)
    margin = span * 0.08
    return low - margin, high + margin


def svg_line_plot(
    path: Path,
    title: str,
    xlabel: str,
    ylabel: str,
    series: list[dict[str, Any]],
    vlines: list[dict[str, Any]] | None = None,
) -> Path:
    width = 1180
    height = 640
    left = 86
    right = 28
    top = 58
    bottom = 78
    plot_w = width - left - right
    plot_h = height - top - bottom
    xs = [x for item in series for x in item["x"]]
    ys = [y for item in series for y in item["y"]]
    x_min, x_max = padded_range(xs)
    y_min, y_max = padded_range(ys)

    def map_x(value: float) -> float:
        return left + (value - x_min) * plot_w / max(1e-12, x_max - x_min)

    def map_y(value: float) -> float:
        return top + plot_h - (value - y_min) * plot_h / max(1e-12, y_max - y_min)

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="white"/>',
        f'<text x="{left}" y="32" font-family="sans-serif" font-size="22" font-weight="700">{svg_escape(title)}</text>',
    ]
    for tick in range(6):
        x = left + tick * plot_w / 5
        value = x_min + tick * (x_max - x_min) / 5
        lines.append(f'<line x1="{x:.2f}" y1="{top}" x2="{x:.2f}" y2="{top + plot_h}" stroke="#e2e8f0" stroke-width="1"/>')
        lines.append(f'<text x="{x:.2f}" y="{height - 38}" text-anchor="middle" font-family="sans-serif" font-size="12" fill="#475569">{value:.4g}</text>')
    for tick in range(6):
        y = top + tick * plot_h / 5
        value = y_max - tick * (y_max - y_min) / 5
        lines.append(f'<line x1="{left}" y1="{y:.2f}" x2="{left + plot_w}" y2="{y:.2f}" stroke="#e2e8f0" stroke-width="1"/>')
        lines.append(f'<text x="{left - 10}" y="{y + 4:.2f}" text-anchor="end" font-family="sans-serif" font-size="12" fill="#475569">{value:.5g}</text>')
    lines.append(f'<rect x="{left}" y="{top}" width="{plot_w}" height="{plot_h}" fill="none" stroke="#94a3b8" stroke-width="1"/>')

    if vlines:
        for item in vlines:
            value = item.get("x")
            if not isinstance(value, (int, float)) or not math.isfinite(value):
                continue
            x = map_x(float(value))
            color = item.get("color", "#111827")
            label = item.get("label", "")
            lines.append(f'<line x1="{x:.2f}" y1="{top}" x2="{x:.2f}" y2="{top + plot_h}" stroke="{color}" stroke-width="2" stroke-dasharray="6 5"/>')
            lines.append(f'<text x="{x + 5:.2f}" y="{top + 18}" font-family="sans-serif" font-size="12" fill="{color}">{svg_escape(label)}</text>')

    for item in series:
        points = []
        for x, y in zip(item["x"], item["y"]):
            if math.isfinite(x) and math.isfinite(y):
                points.append(f"{map_x(x):.2f},{map_y(y):.2f}")
        if points:
            color = item.get("color", "#2563eb")
            width_px = item.get("width", 2)
            opacity = item.get("opacity", 1.0)
            lines.append(f'<polyline points="{" ".join(points)}" fill="none" stroke="{color}" stroke-width="{width_px}" opacity="{opacity}"/>')

    legend_x = left + plot_w - 230
    legend_y = top + 10
    for index, item in enumerate(series):
        y = legend_y + index * 20
        color = item.get("color", "#2563eb")
        label = svg_escape(item.get("label", "series"))
        lines.append(f'<line x1="{legend_x}" y1="{y}" x2="{legend_x + 24}" y2="{y}" stroke="{color}" stroke-width="3"/>')
        lines.append(f'<text x="{legend_x + 32}" y="{y + 4}" font-family="sans-serif" font-size="12" fill="#334155">{label}</text>')

    lines.append(f'<text x="{left + plot_w / 2:.2f}" y="{height - 12}" text-anchor="middle" font-family="sans-serif" font-size="14" fill="#334155">{svg_escape(xlabel)}</text>')
    lines.append(f'<text x="20" y="{top + plot_h / 2:.2f}" transform="rotate(-90 20 {top + plot_h / 2:.2f})" text-anchor="middle" font-family="sans-serif" font-size="14" fill="#334155">{svg_escape(ylabel)}</text>')
    lines.append("</svg>")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def plot_spectrum_overlay(plt: Any, event_dir: Path, out_dir: Path, metadata: dict[str, Any]) -> Path | None:
    reference_path = event_dir / "reference_spectrum.csv"
    partial_path = event_dir / "lock_sweep_partial_estimated.csv"
    frame_path = event_dir / "lock_sweep_frame.csv"
    if not reference_path.exists():
        return None

    reference = read_csv_rows(reference_path)
    partial = read_csv_rows(partial_path) if partial_path.exists() else []
    frame = read_csv_rows(frame_path) if frame_path.exists() else []
    if not has_columns(reference, "ch1_current_mA", "adc_count"):
        return None

    fig, ax = plt.subplots(figsize=(11, 5.5), dpi=140)
    ax.plot(column(reference, "ch1_current_mA"), column(reference, "adc_count"), color="#6d28d9", linewidth=1.2, label="reference spectrum")
    if has_columns(frame, "ch1_current_mA", "adc_count"):
        ax.plot(column(frame, "ch1_current_mA"), column(frame, "adc_count"), color="#94a3b8", linewidth=0.8, alpha=0.55, label="lock sweep full frame")
    if has_columns(partial, "ch1_current_mA", "adc_count"):
        ax.plot(column(partial, "ch1_current_mA"), column(partial, "adc_count"), color="#0284c7", linewidth=1.5, label="estimated lock sweep partial")

    selected_code = first_number(metadata, "selected_code")
    actual_code = first_number(metadata, "actual_code")
    if selected_code is not None:
        add_vertical_marker(ax, selected_code * 10.0 / 65535.0, "selected", "#f59e0b")
    if actual_code is not None:
        add_vertical_marker(ax, actual_code * 10.0 / 65535.0, "locked", "#16a34a")

    ax.set_title("Spectrum Overlay")
    ax.set_xlabel("CH1 current (mA)")
    ax.set_ylabel("ADC count")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    path = out_dir / "spectrum_overlay.png"
    fig.savefig(path)
    plt.close(fig)
    return path


def plot_pd_temperature(plt: Any, event_dir: Path, out_dir: Path) -> Path | None:
    path = event_dir / "pd_temperature_monitor.csv"
    if not path.exists():
        return None
    rows = read_csv_rows(path)
    if not has_columns(rows, "relative_time_s"):
        return None

    t = column(rows, "relative_time_s")
    fig, (ax_pd, ax_temp) = plt.subplots(2, 1, figsize=(11, 7), dpi=140, sharex=True)

    if has_columns(rows, "pd_adc"):
        ax_pd.plot(t, column(rows, "pd_adc"), color="#2563eb", linewidth=1.1, label="PD ADC")
    ax_pd.axvline(0, color="#111827", linestyle="--", linewidth=1, alpha=0.6)
    ax_pd.set_ylabel("PD ADC count")
    ax_pd.grid(True, alpha=0.25)
    ax_pd.legend(loc="best")

    if has_columns(rows, "temp_filtered_c"):
        ax_temp.plot(t, column(rows, "temp_filtered_c"), color="#2563eb", linewidth=1.1, label="filtered temperature")
    if has_columns(rows, "temp_measured_c"):
        ax_temp.plot(t, column(rows, "temp_measured_c"), color="#64748b", linewidth=0.9, alpha=0.7, label="measured temperature")
    if has_columns(rows, "temp_target_c"):
        ax_temp.plot(t, column(rows, "temp_target_c"), color="#ef4444", linewidth=1.0, label="target temperature")
    ax_temp.axvline(0, color="#111827", linestyle="--", linewidth=1, alpha=0.6)
    ax_temp.set_xlabel("time from lock command (s)")
    ax_temp.set_ylabel("temperature (C)")
    ax_temp.grid(True, alpha=0.25)
    ax_temp.legend(loc="best")

    fig.suptitle("PD and Temperature Monitor")
    fig.tight_layout()
    out = out_dir / "pd_temperature_monitor.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_lock_status(plt: Any, event_dir: Path, out_dir: Path) -> Path | None:
    path = event_dir / "lock_status.csv"
    if not path.exists():
        return None
    rows = read_csv_rows(path)
    if not has_columns(rows, "relative_time_s"):
        return None
    t = column(rows, "relative_time_s")

    fig, ax = plt.subplots(figsize=(11, 5.5), dpi=140)
    if has_columns(rows, "pd_adc"):
        ax.plot(t, column(rows, "pd_adc"), color="#2563eb", linewidth=1.0, label="PD ADC")
    if has_columns(rows, "target_adc"):
        ax.plot(t, column(rows, "target_adc"), color="#ef4444", linewidth=1.0, label="target ADC")
    if has_columns(rows, "lock_error"):
        ax2 = ax.twinx()
        ax2.plot(t, column(rows, "lock_error"), color="#7c3aed", linewidth=0.9, label="lock error")
        ax2.set_ylabel("lock error (ADC count)")
        ax2.legend(loc="upper right")
    ax.axvline(0, color="#111827", linestyle="--", linewidth=1, alpha=0.6)
    ax.set_title("Lock Status")
    ax.set_xlabel("time from lock command (s)")
    ax.set_ylabel("ADC count")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="upper left")
    fig.tight_layout()
    out = out_dir / "lock_status.png"
    fig.savefig(out)
    plt.close(fig)
    return out


def plot_spectrum_overlay_svg(event_dir: Path, out_dir: Path, metadata: dict[str, Any]) -> list[Path]:
    reference_path = event_dir / "reference_spectrum.csv"
    if not reference_path.exists():
        return []
    reference = read_csv_rows(reference_path)
    partial = read_csv_rows(event_dir / "lock_sweep_partial_estimated.csv") if (event_dir / "lock_sweep_partial_estimated.csv").exists() else []
    frame = read_csv_rows(event_dir / "lock_sweep_frame.csv") if (event_dir / "lock_sweep_frame.csv").exists() else []
    if not has_columns(reference, "ch1_current_mA", "adc_count"):
        return []
    series = [
        {
            "x": column(reference, "ch1_current_mA"),
            "y": column(reference, "adc_count"),
            "label": "reference spectrum",
            "color": "#6d28d9",
            "width": 2,
        }
    ]
    if has_columns(frame, "ch1_current_mA", "adc_count"):
        series.append(
            {
                "x": column(frame, "ch1_current_mA"),
                "y": column(frame, "adc_count"),
                "label": "lock sweep full frame",
                "color": "#94a3b8",
                "width": 1.2,
                "opacity": 0.65,
            }
        )
    if has_columns(partial, "ch1_current_mA", "adc_count"):
        series.append(
            {
                "x": column(partial, "ch1_current_mA"),
                "y": column(partial, "adc_count"),
                "label": "estimated lock sweep partial",
                "color": "#0284c7",
                "width": 2.4,
            }
        )
    vlines = []
    selected_code = first_number(metadata, "selected_code")
    actual_code = first_number(metadata, "actual_code")
    if selected_code is not None:
        vlines.append({"x": selected_code * 10.0 / 65535.0, "label": "selected", "color": "#f59e0b"})
    if actual_code is not None:
        vlines.append({"x": actual_code * 10.0 / 65535.0, "label": "locked", "color": "#16a34a"})
    return [svg_line_plot(out_dir / "spectrum_overlay.svg", "Spectrum Overlay", "CH1 current (mA)", "ADC count", series, vlines)]


def plot_pd_temperature_svg(event_dir: Path, out_dir: Path) -> list[Path]:
    path = event_dir / "pd_temperature_monitor.csv"
    if not path.exists():
        return []
    rows = read_csv_rows(path)
    if not has_columns(rows, "relative_time_s"):
        return []
    t = column(rows, "relative_time_s")
    generated: list[Path] = []
    if has_columns(rows, "pd_adc"):
        generated.append(
            svg_line_plot(
                out_dir / "pd_monitor.svg",
                "PD Monitor",
                "time from lock command (s)",
                "PD ADC count",
                [{"x": t, "y": column(rows, "pd_adc"), "label": "PD ADC", "color": "#2563eb"}],
                [{"x": 0.0, "label": "lock command", "color": "#111827"}],
            )
        )
    temp_series = []
    if has_columns(rows, "temp_filtered_c"):
        temp_series.append({"x": t, "y": column(rows, "temp_filtered_c"), "label": "filtered temperature", "color": "#2563eb"})
    if has_columns(rows, "temp_measured_c"):
        temp_series.append({"x": t, "y": column(rows, "temp_measured_c"), "label": "measured temperature", "color": "#64748b"})
    if has_columns(rows, "temp_target_c"):
        temp_series.append({"x": t, "y": column(rows, "temp_target_c"), "label": "target temperature", "color": "#ef4444"})
    if temp_series:
        generated.append(
            svg_line_plot(
                out_dir / "temperature_monitor.svg",
                "Temperature Monitor",
                "time from lock command (s)",
                "temperature (C)",
                temp_series,
                [{"x": 0.0, "label": "lock command", "color": "#111827"}],
            )
        )
    return generated


def plot_lock_status_svg(event_dir: Path, out_dir: Path) -> list[Path]:
    path = event_dir / "lock_status.csv"
    if not path.exists():
        return []
    rows = read_csv_rows(path)
    if not has_columns(rows, "relative_time_s"):
        return []
    t = column(rows, "relative_time_s")
    generated: list[Path] = []
    adc_series = []
    if has_columns(rows, "pd_adc"):
        adc_series.append({"x": t, "y": column(rows, "pd_adc"), "label": "PD ADC", "color": "#2563eb"})
    if has_columns(rows, "target_adc"):
        adc_series.append({"x": t, "y": column(rows, "target_adc"), "label": "target ADC", "color": "#ef4444"})
    if adc_series:
        generated.append(
            svg_line_plot(
                out_dir / "lock_pd_target.svg",
                "Lock PD and Target",
                "time from lock command (s)",
                "ADC count",
                adc_series,
                [{"x": 0.0, "label": "lock command", "color": "#111827"}],
            )
        )
    if has_columns(rows, "lock_error"):
        generated.append(
            svg_line_plot(
                out_dir / "lock_error.svg",
                "Lock Error",
                "time from lock command (s)",
                "lock error (ADC count)",
                [{"x": t, "y": column(rows, "lock_error"), "label": "lock error", "color": "#7c3aed"}],
                [{"x": 0.0, "label": "lock command", "color": "#111827"}],
            )
        )
    return generated


def write_summary(event_dir: Path, out_dir: Path, metadata: dict[str, Any], generated: Iterable[Path]) -> Path:
    path = out_dir / "summary.txt"
    lines = [
        f"recording_dir: {event_dir}",
        f"run_name: {metadata.get('run_name', '')}",
        f"event_name: {metadata.get('event_name', '')}",
        f"lock_method: {metadata.get('lock_method', '')}",
        f"selected_code: {metadata.get('selected_code', '')}",
        f"actual_code: {metadata.get('actual_code', '')}",
        f"selected_reference_index: {metadata.get('selected_reference_index', '')}",
        f"actual_reference_index: {metadata.get('actual_reference_index', '')}",
        "",
        "generated_plots:",
    ]
    lines.extend(f"  {item.name}" for item in generated)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def plot_recording(event_dir: Path, output: str | None = None) -> list[Path]:
    event_dir = event_dir.expanduser().resolve()
    if not event_dir.exists():
        raise FileNotFoundError(event_dir)
    out_dir = resolve_output_dir(event_dir, output)
    out_dir.mkdir(parents=True, exist_ok=True)
    metadata = read_json(event_dir / "metadata.json")
    plt = setup_matplotlib()

    if plt is not None:
        generated = [
            plot_spectrum_overlay(plt, event_dir, out_dir, metadata),
            plot_pd_temperature(plt, event_dir, out_dir),
            plot_lock_status(plt, event_dir, out_dir),
        ]
        paths = [path for path in generated if path is not None]
    else:
        paths = []
        paths.extend(plot_spectrum_overlay_svg(event_dir, out_dir, metadata))
        paths.extend(plot_pd_temperature_svg(event_dir, out_dir))
        paths.extend(plot_lock_status_svg(event_dir, out_dir))
    paths.append(write_summary(event_dir, out_dir, metadata, paths))
    return paths


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Replot Butterfly Laser lock recording bundles.")
    parser.add_argument("path", help="Recording event directory, run directory, or Butterfly_Laser_Data directory")
    parser.add_argument("--output", help="Output directory. Defaults to <event>/plots for one event.")
    parser.add_argument("--recursive", action="store_true", help="Find all metadata.json files below path and plot each event.")
    args = parser.parse_args(argv)

    root = Path(args.path)
    event_dirs = discover_recording_dirs(root) if args.recursive or not (root / "metadata.json").exists() else [root.expanduser().resolve()]
    if not event_dirs:
        print(f"No recording directories found under {root}", file=sys.stderr)
        return 1

    for event_dir in event_dirs:
        output = args.output
        if args.output and len(event_dirs) > 1:
            output = str(Path(args.output).expanduser().resolve() / event_dir.name)
        generated = plot_recording(event_dir, output)
        print(f"{event_dir}:")
        for path in generated:
            print(f"  wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
