export const DEFAULT_PD_ZERO_ADC_CODE = 27034;
export const DEFAULT_TZ_OHM = 2000;
export const DEFAULT_SCAN_SCALE_COUNTS = 4000;
export const DEFAULT_SCAN_SCALE_UM = 530;
export const DEFAULT_UM_PER_COUNT = DEFAULT_SCAN_SCALE_UM / DEFAULT_SCAN_SCALE_COUNTS;
